### ISSUE TITLE
Intro to NN - 14. Backpropagation

### ISSUE THREAD

**Issue by onemodtwo** [udacity/dlnd-issue-reports#94]
In this lesson we find the following:

"From this example, you can see one of the effects of using the sigmoid function for the activations. The maximum derivative of the sigmoid function is 0.5, so the errors in the output layer get scaled by at least half, and errors in the hidden layer are scaled down by at least a quarter."

If f is the sigmoid, then f' = f(1 - f). This quadratic has a max at (.5, .25), so the gradient scales the weights by a factor <= .25 at each layer.

**Comment by dhruvp** [comment]
This is fixed now. Thanks for letting us know @onemodtwo!

**Comment by onemodtwo** [comment]
It's only partially fixed. The words also need fixing. They still read as in the original: "... so the errors in the output layer get scaled by at least half, and errors in the hidden layer are scaled down by at least a quarter."

Should read quarter and eighth, respectively.

**Comment by onemodtwo** [comment]
Almost, but not completely, fixed. See my follow up comment on waffle.
